childernofstudyingatpresent_index:
    path:     /
    defaults: { _controller: "ApplicationBundle:ChildernOfStudyingAtPresent:index" }
    methods:  GET

childernofstudyingatpresent_show:
    path:     /{id}/show
    defaults: { _controller: "ApplicationBundle:ChildernOfStudyingAtPresent:show" }
    methods:  GET

childernofstudyingatpresent_new:
    path:     /new
    defaults: { _controller: "ApplicationBundle:ChildernOfStudyingAtPresent:new" }
    methods:  [GET, POST]

childernofstudyingatpresent_edit:
    path:     /{id}/edit
    defaults: { _controller: "ApplicationBundle:ChildernOfStudyingAtPresent:edit" }
    methods:  [GET, POST]

childernofstudyingatpresent_delete:
    path:     /{id}/delete
    defaults: { _controller: "ApplicationBundle:ChildernOfStudyingAtPresent:delete" }
    methods:  DELETE
