childrenofstaff_index:
    path:     /
    defaults: { _controller: "ApplicationBundle:ChildrenOfStaff:index" }
    methods:  GET

childrenofstaff_show:
    path:     /{id}/show
    defaults: { _controller: "ApplicationBundle:ChildrenOfStaff:show" }
    methods:  GET

childrenofstaff_new:
    path:     /new
    defaults: { _controller: "ApplicationBundle:ChildrenOfStaff:new" }
    methods:  [GET, POST]

childrenofstaff_edit:
    path:     /{id}/edit
    defaults: { _controller: "ApplicationBundle:ChildrenOfStaff:edit" }
    methods:  [GET, POST]

childrenofstaff_delete:
    path:     /{id}/delete
    defaults: { _controller: "ApplicationBundle:ChildrenOfStaff:delete" }
    methods:  DELETE