childrenofotoeos_index:
    path:     /
    defaults: { _controller: "ApplicationBundle:ChildrenOfOtoeos:index" }
    methods:  GET

childrenofotoeos_show:
    path:     /{id}/show
    defaults: { _controller: "ApplicationBundle:ChildrenOfOtoeos:show" }
    methods:  GET

childrenofotoeos_new:
    path:     /new
    defaults: { _controller: "ApplicationBundle:ChildrenOfOtoeos:new" }
    methods:  [GET, POST]

childrenofotoeos_edit:
    path:     /{id}/edit
    defaults: { _controller: "ApplicationBundle:ChildrenOfOtoeos:edit" }
    methods:  [GET, POST]

childrenofotoeos_delete:
    path:     /{id}/delete
    defaults: { _controller: "ApplicationBundle:ChildrenOfOtoeos:delete" }
    methods:  DELETE
