previlege_index:
    path:     /
    defaults: { _controller: "ApplicationBundle:Previlege:index" }
    methods:  GET

previlege_show:
    path:     /{id}/show
    defaults: { _controller: "ApplicationBundle:Previlege:show" }
    methods:  GET

previlege_new:
    path:     /new
    defaults: { _controller: "ApplicationBundle:Previlege:new" }
    methods:  [GET, POST]

previlege_edit:
    path:     /{id}/edit
    defaults: { _controller: "ApplicationBundle:Previlege:edit" }
    methods:  [GET, POST]

previlege_delete:
    path:     /{id}/delete
    defaults: { _controller: "ApplicationBundle:Previlege:delete" }
    methods:  DELETE
