role_index:
    path:     /
    defaults: { _controller: "ApplicationBundle:Role:index" }
    methods:  GET

role_show:
    path:     /{id}/show
    defaults: { _controller: "ApplicationBundle:Role:show" }
    methods:  GET

role_new:
    path:     /new
    defaults: { _controller: "ApplicationBundle:Role:new" }
    methods:  [GET, POST]

role_edit:
    path:     /{id}/edit
    defaults: { _controller: "ApplicationBundle:Role:edit" }
    methods:  [GET, POST]

role_delete:
    path:     /{id}/delete
    defaults: { _controller: "ApplicationBundle:Role:delete" }
    methods:  DELETE
