school_index:
    path:     /
    defaults: { _controller: "ApplicationBundle:School:index" }
    methods:  GET

school_show:
    path:     /{id}/show
    defaults: { _controller: "ApplicationBundle:School:show" }
    methods:  GET

school_new:
    path:     /new
    defaults: { _controller: "ApplicationBundle:School:new" }
    methods:  [GET, POST]

school_edit:
    path:     /{id}/edit
    defaults: { _controller: "ApplicationBundle:School:edit" }
    methods:  [GET, POST]

school_delete:
    path:     /{id}/delete
    defaults: { _controller: "ApplicationBundle:School:delete" }
    methods:  DELETE
