application:
    resource: "@ApplicationBundle/Resources/config/routing.yml"
    prefix:   /

applicant:
    resource: "@ApplicantBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
