<?php

namespace Proxies\__CG__\ApplicantBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Applicant extends \ApplicantBundle\Entity\Applicant implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'ApplicantBundle\\Entity\\Applicant' . "\0" . 'nameInFull', '' . "\0" . 'ApplicantBundle\\Entity\\Applicant' . "\0" . 'nameInInitials', '' . "\0" . 'ApplicantBundle\\Entity\\Applicant' . "\0" . 'permanentAddress', '' . "\0" . 'ApplicantBundle\\Entity\\Applicant' . "\0" . 'gramaNiladariDivion', '' . "\0" . 'ApplicantBundle\\Entity\\Applicant' . "\0" . 'divsionalScretaryArea', '' . "\0" . 'ApplicantBundle\\Entity\\Applicant' . "\0" . 'district', '' . "\0" . 'ApplicantBundle\\Entity\\Applicant' . "\0" . 'dob', '' . "\0" . 'ApplicantBundle\\Entity\\Applicant' . "\0" . 'nic', '' . "\0" . 'ApplicantBundle\\Entity\\Applicant' . "\0" . 'wetherSrilankan', '' . "\0" . 'ApplicantBundle\\Entity\\Applicant' . "\0" . 'noYearsInElectoralRegister', '' . "\0" . 'ApplicantBundle\\Entity\\Applicant' . "\0" . 'noSchoolsLocatedCloser', '' . "\0" . 'ApplicantBundle\\Entity\\Applicant' . "\0" . 'religion', '' . "\0" . 'ApplicantBundle\\Entity\\Applicant' . "\0" . 'id', '' . "\0" . 'ApplicantBundle\\Entity\\Applicant' . "\0" . 'school');
        }

        return array('__isInitialized__', '' . "\0" . 'ApplicantBundle\\Entity\\Applicant' . "\0" . 'nameInFull', '' . "\0" . 'ApplicantBundle\\Entity\\Applicant' . "\0" . 'nameInInitials', '' . "\0" . 'ApplicantBundle\\Entity\\Applicant' . "\0" . 'permanentAddress', '' . "\0" . 'ApplicantBundle\\Entity\\Applicant' . "\0" . 'gramaNiladariDivion', '' . "\0" . 'ApplicantBundle\\Entity\\Applicant' . "\0" . 'divsionalScretaryArea', '' . "\0" . 'ApplicantBundle\\Entity\\Applicant' . "\0" . 'district', '' . "\0" . 'ApplicantBundle\\Entity\\Applicant' . "\0" . 'dob', '' . "\0" . 'ApplicantBundle\\Entity\\Applicant' . "\0" . 'nic', '' . "\0" . 'ApplicantBundle\\Entity\\Applicant' . "\0" . 'wetherSrilankan', '' . "\0" . 'ApplicantBundle\\Entity\\Applicant' . "\0" . 'noYearsInElectoralRegister', '' . "\0" . 'ApplicantBundle\\Entity\\Applicant' . "\0" . 'noSchoolsLocatedCloser', '' . "\0" . 'ApplicantBundle\\Entity\\Applicant' . "\0" . 'religion', '' . "\0" . 'ApplicantBundle\\Entity\\Applicant' . "\0" . 'id', '' . "\0" . 'ApplicantBundle\\Entity\\Applicant' . "\0" . 'school');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Applicant $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setNameInFull($nameInFull)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNameInFull', array($nameInFull));

        return parent::setNameInFull($nameInFull);
    }

    /**
     * {@inheritDoc}
     */
    public function getNameInFull()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNameInFull', array());

        return parent::getNameInFull();
    }

    /**
     * {@inheritDoc}
     */
    public function setNameInInitials($nameInInitials)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNameInInitials', array($nameInInitials));

        return parent::setNameInInitials($nameInInitials);
    }

    /**
     * {@inheritDoc}
     */
    public function getNameInInitials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNameInInitials', array());

        return parent::getNameInInitials();
    }

    /**
     * {@inheritDoc}
     */
    public function setPermanentAddress($permanentAddress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPermanentAddress', array($permanentAddress));

        return parent::setPermanentAddress($permanentAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getPermanentAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPermanentAddress', array());

        return parent::getPermanentAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setGramaNiladariDivion($gramaNiladariDivion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGramaNiladariDivion', array($gramaNiladariDivion));

        return parent::setGramaNiladariDivion($gramaNiladariDivion);
    }

    /**
     * {@inheritDoc}
     */
    public function getGramaNiladariDivion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGramaNiladariDivion', array());

        return parent::getGramaNiladariDivion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDivsionalScretaryArea($divsionalScretaryArea)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDivsionalScretaryArea', array($divsionalScretaryArea));

        return parent::setDivsionalScretaryArea($divsionalScretaryArea);
    }

    /**
     * {@inheritDoc}
     */
    public function getDivsionalScretaryArea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDivsionalScretaryArea', array());

        return parent::getDivsionalScretaryArea();
    }

    /**
     * {@inheritDoc}
     */
    public function setDistrict($district)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDistrict', array($district));

        return parent::setDistrict($district);
    }

    /**
     * {@inheritDoc}
     */
    public function getDistrict()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDistrict', array());

        return parent::getDistrict();
    }

    /**
     * {@inheritDoc}
     */
    public function setDob($dob)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDob', array($dob));

        return parent::setDob($dob);
    }

    /**
     * {@inheritDoc}
     */
    public function getDob()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDob', array());

        return parent::getDob();
    }

    /**
     * {@inheritDoc}
     */
    public function setNic($nic)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNic', array($nic));

        return parent::setNic($nic);
    }

    /**
     * {@inheritDoc}
     */
    public function getNic()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNic', array());

        return parent::getNic();
    }

    /**
     * {@inheritDoc}
     */
    public function setWetherSrilankan($wetherSrilankan)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWetherSrilankan', array($wetherSrilankan));

        return parent::setWetherSrilankan($wetherSrilankan);
    }

    /**
     * {@inheritDoc}
     */
    public function getWetherSrilankan()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWetherSrilankan', array());

        return parent::getWetherSrilankan();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoYearsInElectoralRegister($noYearsInElectoralRegister)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoYearsInElectoralRegister', array($noYearsInElectoralRegister));

        return parent::setNoYearsInElectoralRegister($noYearsInElectoralRegister);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoYearsInElectoralRegister()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoYearsInElectoralRegister', array());

        return parent::getNoYearsInElectoralRegister();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoSchoolsLocatedCloser($noSchoolsLocatedCloser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoSchoolsLocatedCloser', array($noSchoolsLocatedCloser));

        return parent::setNoSchoolsLocatedCloser($noSchoolsLocatedCloser);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoSchoolsLocatedCloser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoSchoolsLocatedCloser', array());

        return parent::getNoSchoolsLocatedCloser();
    }

    /**
     * {@inheritDoc}
     */
    public function setReligion($religion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReligion', array($religion));

        return parent::setReligion($religion);
    }

    /**
     * {@inheritDoc}
     */
    public function getReligion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReligion', array());

        return parent::getReligion();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function addSchool(\ApplicantBundle\Entity\School $school)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSchool', array($school));

        return parent::addSchool($school);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSchool(\ApplicantBundle\Entity\School $school)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSchool', array($school));

        return parent::removeSchool($school);
    }

    /**
     * {@inheritDoc}
     */
    public function getSchool()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSchool', array());

        return parent::getSchool();
    }

}
