<?php

namespace Proxies\__CG__\ApplicantBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ChildernOfStudyingAtPresent extends \ApplicantBundle\Entity\ChildernOfStudyingAtPresent implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'ApplicantBundle\\Entity\\ChildernOfStudyingAtPresent' . "\0" . 'nameInFull', '' . "\0" . 'ApplicantBundle\\Entity\\ChildernOfStudyingAtPresent' . "\0" . 'nameInInitial', '' . "\0" . 'ApplicantBundle\\Entity\\ChildernOfStudyingAtPresent' . "\0" . 'grade', '' . "\0" . 'ApplicantBundle\\Entity\\ChildernOfStudyingAtPresent' . "\0" . 'addmissionNo', '' . "\0" . 'ApplicantBundle\\Entity\\ChildernOfStudyingAtPresent' . "\0" . 'addmissionGrade', '' . "\0" . 'ApplicantBundle\\Entity\\ChildernOfStudyingAtPresent' . "\0" . 'gradesSpent', '' . "\0" . 'ApplicantBundle\\Entity\\ChildernOfStudyingAtPresent' . "\0" . 'id', '' . "\0" . 'ApplicantBundle\\Entity\\ChildernOfStudyingAtPresent' . "\0" . 'school', '' . "\0" . 'ApplicantBundle\\Entity\\ChildernOfStudyingAtPresent' . "\0" . 'applicant');
        }

        return array('__isInitialized__', '' . "\0" . 'ApplicantBundle\\Entity\\ChildernOfStudyingAtPresent' . "\0" . 'nameInFull', '' . "\0" . 'ApplicantBundle\\Entity\\ChildernOfStudyingAtPresent' . "\0" . 'nameInInitial', '' . "\0" . 'ApplicantBundle\\Entity\\ChildernOfStudyingAtPresent' . "\0" . 'grade', '' . "\0" . 'ApplicantBundle\\Entity\\ChildernOfStudyingAtPresent' . "\0" . 'addmissionNo', '' . "\0" . 'ApplicantBundle\\Entity\\ChildernOfStudyingAtPresent' . "\0" . 'addmissionGrade', '' . "\0" . 'ApplicantBundle\\Entity\\ChildernOfStudyingAtPresent' . "\0" . 'gradesSpent', '' . "\0" . 'ApplicantBundle\\Entity\\ChildernOfStudyingAtPresent' . "\0" . 'id', '' . "\0" . 'ApplicantBundle\\Entity\\ChildernOfStudyingAtPresent' . "\0" . 'school', '' . "\0" . 'ApplicantBundle\\Entity\\ChildernOfStudyingAtPresent' . "\0" . 'applicant');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ChildernOfStudyingAtPresent $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setNameInFull($nameInFull)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNameInFull', array($nameInFull));

        return parent::setNameInFull($nameInFull);
    }

    /**
     * {@inheritDoc}
     */
    public function getNameInFull()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNameInFull', array());

        return parent::getNameInFull();
    }

    /**
     * {@inheritDoc}
     */
    public function setNameInInitial($nameInInitial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNameInInitial', array($nameInInitial));

        return parent::setNameInInitial($nameInInitial);
    }

    /**
     * {@inheritDoc}
     */
    public function getNameInInitial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNameInInitial', array());

        return parent::getNameInInitial();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrade($grade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrade', array($grade));

        return parent::setGrade($grade);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrade', array());

        return parent::getGrade();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddmissionNo($addmissionNo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddmissionNo', array($addmissionNo));

        return parent::setAddmissionNo($addmissionNo);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddmissionNo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddmissionNo', array());

        return parent::getAddmissionNo();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddmissionGrade($addmissionGrade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddmissionGrade', array($addmissionGrade));

        return parent::setAddmissionGrade($addmissionGrade);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddmissionGrade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddmissionGrade', array());

        return parent::getAddmissionGrade();
    }

    /**
     * {@inheritDoc}
     */
    public function setGradesSpent($gradesSpent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGradesSpent', array($gradesSpent));

        return parent::setGradesSpent($gradesSpent);
    }

    /**
     * {@inheritDoc}
     */
    public function getGradesSpent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGradesSpent', array());

        return parent::getGradesSpent();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSchool(\ApplicantBundle\Entity\School $school = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSchool', array($school));

        return parent::setSchool($school);
    }

    /**
     * {@inheritDoc}
     */
    public function getSchool()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSchool', array());

        return parent::getSchool();
    }

    /**
     * {@inheritDoc}
     */
    public function setApplicant(\ApplicantBundle\Entity\Applicant $applicant = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApplicant', array($applicant));

        return parent::setApplicant($applicant);
    }

    /**
     * {@inheritDoc}
     */
    public function getApplicant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApplicant', array());

        return parent::getApplicant();
    }

}
