application_homepage:
    path:     /
    defaults: { _controller: ApplicationBundle:Default:index }

web_applicant:
    resource: "@ApplicationBundle/Resources/config/routing/applicant.yml"
    prefix:   /applicant1

web_child:
    resource: "@ApplicationBundle/Resources/config/routing/child.yml"
    prefix:   /child

web_school:
    resource: "@ApplicationBundle/Resources/config/routing/school.yml"
    prefix:   /school

web_childOfStaff:
    resource: "@ApplicationBundle/Resources/config/routing/ChildOfStaff.yml"
    prefix:   /childOfStaff

web_childOfOtoeos:
    resource: "@ApplicationBundle/Resources/config/routing/childrenofotoeos.yml"
    prefix:   /childOfOteoes

web_user:
    resource: "@ApplicationBundle/Resources/config/routing/user.yml"
    prefix:   /user

web_role:
    resource: "@ApplicationBundle/Resources/config/routing/role.yml"
    prefix:   /role